In [8]:
import sqlite3 as sql
import pandas as pd
from IPython.display import display

In [60]:
conn = sql.connect('Tables.db')
cursor = conn.cursor()

In [34]:
pd.read_sql_query("SELECT * FROM sqlite_sequence",conn)

Empty DataFrame
Columns: [name, seq]
Index: []

In [32]:
tb_books = pd.read_sql_query("SELECT * FROM books",conn)

In [19]:
df_books = pd.read_csv('datasets/books_data/books.csv',encoding='latin1',delimiter=';',on_bad_lines='skip')

C:\Users\manan\AppData\Local\Temp\ipykernel_17012\3094420647.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  df_books = pd.read_csv('datasets/books_data/books.csv',encoding='latin1',delimiter=';',on_bad_lines='skip')

In [28]:
df_books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271357 non-null  float64
 4   Publisher            271358 non-null  str
dtypes: float64(1), str(4)
memory usage: 10.4 MB

In [27]:
# df_books.drop(columns=['Image-URL-S','Image-URL-M', 'Image-URL-L'],inplace=True)
df_books['Year-Of-Publication'] = pd.to_numeric(df_books['Year-Of-Publication'],errors='coerce')

In [62]:
df_books.rename(columns={'Book-Title':'Book_Title',
                         'Year-Of-Publication':'Year_Of_Publication',
                         'Book-Author':'Book_Author'},inplace=True)

In [47]:
tb_books

Empty DataFrame
Columns: [book_id, author_id, category_id, title, published_year, total_copies, available_copies, average_rating]
Index: []

In [63]:
sql_books = df_books.to_sql('bigbooks',conn)
# cursor.execute('DROP TABLE bigbooks')

In [64]:
pd.read_sql_query('SELECT * FROM bigbooks',conn)

,index,ISBN,Book_Title,Book_Author,Year_Of_Publication,Publisher
0,0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press
1,1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada
2,2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial
3,3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux
4,4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company
...,...,...,...,...,...,...
271355,271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988.0,Random House Childrens Pub (Mm)
271356,271356,0525447644,From One to One Hundred,Teri Sloat,1991.0,Dutton Books
271357,271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004.0,HarperSanFrancisco
271358,271358,0192126040,Republic (World's Classics),Plato,1996.0,Oxford University Press
271359,271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000.0,McGraw-Hill Humanities/Social Sciences/Languages

In [108]:
query = """
SELECT
book_id,
Book_Author,
author_id
FROM (
SELECT
ISBN AS book_id,
COALESCE(Book_Author,'unknown') AS Book_Author,
DENSE_RANK() OVER(ORDER BY Book_Author) AS author_id
FROM bigbooks
)t
"""

In [109]:
pd.read_sql_query(query,conn)

           book_id             Book_Author  author_id
0       0751352497                 unknown          1
1       9627982032                 unknown          1
2       0312956762                D. Chiel          2
3       034545006X            J. D. Landis          3
4       1579651372             Mimma Balia          4
...            ...                     ...        ...
271355  3518067540     Ã?dÃ¶n von HorvÃ¡th     102020
271356  3518375547     Ã?dÃ¶n von HorvÃ¡th     102020
271357  3518188070  Ã?Â?dÃ?Â¶n von Horvath     102021
271358  2268045757          Ã?Â?pictÃ?Â¨te     102022
271359  2290048763          Ã?Â?ric Holder     102023

[271360 rows x 3 columns]

In [69]:
df_books.nunique()

ISBN                   271360
Book_Title             242135
Book_Author            102022
Year_Of_Publication       116
Publisher               16807
dtype: int64