In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
conn = sql.connect('Tables.db')
cursor= conn.cursor()

In [3]:
df= pd.read_csv('datasets/books_data/books.csv',
                delimiter=';', encoding='latin1',
                on_bad_lines='skip')
df.drop(columns=['Image-URL-S', 'Image-URL-M', 'Image-URL-L'], inplace=True)
print(df.head())
print(df.columns)

         ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology
1  0002005018                                       Clara Callan
2  0060973129                               Decision in Normandy
3  0374157065  Flu: The Story of the Great Influenza Pandemic...
4  0393045218                             The Mummies of Urumchi

            Book-Author Year-Of-Publication                   Publisher
0    Mark P. O. Morford                2002     Oxford University Press
1  Richard Bruce Wright                2001       HarperFlamingo Canada
2          Carlo D'Este                1991             HarperPerennial
3      Gina Bari Kolata                1999        Farrar Straus Giroux
4       E. J. W. Barber                1999  W. W. Norton &amp; Company
Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication',
       'Publisher'],
      dtype='str')

C:\Users\manan\AppData\Local\Temp\ipykernel_9348\3663246791.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('datasets/books_data/books.csv',

In [4]:
df['Year-Of-Publication'] = pd.to_numeric(df['Year-Of-Publication'], errors="coerce")

In [5]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271357 non-null  float64
 4   Publisher            271358 non-null  str
dtypes: float64(1), str(4)
memory usage: 10.4 MB

In [7]:
df.describe(include=[str])

              ISBN      Book-Title      Book-Author  Publisher
count       271360          271360           271358     271358
unique      271360          242135           102022      16807
top     0195153448  Selected Poems  Agatha Christie  Harlequin
freq             1              27              632       7535

In [8]:
for col in df.columns:
    print(df[col].nunique())
    print(df[[col]].count())
print(df.isna().sum())

271360
ISBN    271360
dtype: int64
242135
Book-Title    271360
dtype: int64
102022
Book-Author    271358
dtype: int64
116
Year-Of-Publication    271357
dtype: int64
16807
Publisher    271358
dtype: int64
ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    3
Publisher              2
dtype: int64

In [9]:
df.dropna(how='any',inplace=True)

In [10]:
print(df.isna().sum())

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 271353 entries, 0 to 271359
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271353 non-null  str
 1   Book-Title           271353 non-null  str
 2   Book-Author          271353 non-null  str
 3   Year-Of-Publication  271353 non-null  float64
 4   Publisher            271353 non-null  str
dtypes: float64(1), str(4)
memory usage: 12.4 MB

In [12]:


pd.read_sql_query("SELECT * FROM books",conn)

Empty DataFrame
Columns: [book_id, author_id, category_id, title, published_year, total_copies, available_copies, average_rating]
Index: []

In [13]:
pd.read_sql_query("SELECT * FROM categories",conn)

Empty DataFrame
Columns: [category_id, category_name]
Index: []

In [14]:
df_ratings = pd.read_csv('datasets/books_data/ratings.csv',
                delimiter=';', encoding='latin1',
                on_bad_lines='skip')

In [15]:
df_ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [16]:
df_users = pd.read_csv('datasets/books_data/users.csv',
                delimiter=';', encoding='latin1',
                on_bad_lines='skip')

In [17]:
df_users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [18]:
df_books = df.sample(1000)

In [21]:
cursor.executemany("""INSERT INTO books (book_id, title, published_year)
    VALUES(?,?,?)
""",df_books[['ISBN','Book-Title','Year-Of-Publication']].itertuples(index=False)  )

IntegrityError: UNIQUE constraint failed: books.book_id

In [20]:
df_books.info()

<class 'pandas.DataFrame'>
Index: 1000 entries, 36811 to 60274
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ISBN                 1000 non-null   str
 1   Book-Title           1000 non-null   str
 2   Book-Author          1000 non-null   str
 3   Year-Of-Publication  1000 non-null   float64
 4   Publisher            1000 non-null   str
dtypes: float64(1), str(4)
memory usage: 46.9 KB

In [22]:
df = pd.read_sql_query("SELECT * FROM books",conn)

In [23]:
df

,book_id,author_id,category_id,title,published_year,total_copies,available_copies,average_rating
0,0525671714,None,None,Rivals,1985,None,None,None
1,0140028374,None,None,The Highland clearances,1969,None,None,None
2,0500018626,None,None,The Most Beautiful Villages of Burgundy (Most ...,1998,None,None,None
3,1891575031,None,None,The Thoughtstorm Manual : An Evolution In Huma...,1999,None,None,None
4,0806938781,None,None,Golf Swing Basics (Golf Books for Father's Day),1996,None,None,None
...,...,...,...,...,...,...,...,...
995,1576730980,None,None,Keeper of the Springs,1997,None,None,None
996,8420633933,None,None,"Proceso, El",1999,None,None,None
997,3518399276,None,None,Das Fest des Ziegenbocks.,2002,None,None,None
998,0749300965,None,None,It Gets Better After Cairo,1990,None,None,None
999,0393009564,None,None,Chesapeake in the Seventeenth Century,1980,None,None,None

In [ ]:
cursor.executemany("""INSERT INTO authors (book_id, title, published_year)
    VALUES(?,?,?)
""",df_books[['ISBN','Book-Title','Year-Of-Publication']].itertuples(index=False)  )